### ISSUE TITLE
感谢作者的工作，请问会开源fedlora的代码吗？

### ISSUE THREAD

**Issue by XXiaoY** [FDU-INC/Split_LoRA#1]
感谢作者的工作，请问会开源fedlora的代码吗？

**Comment by jingluo168** [comment]
> 我在尝试复现的时候，发现fedlora这个baseline效果非常差，不知道作者能否开源相关代码？

景罗168
jingluo168 2 minutes ago 日评论
[景罗168](https://github.com/jingluo168)
[2 minutes ago](https://github.com/FDU-INC/SplitFM/issues/1#issuecomment-2804652911)
您好，想请教您，怎样能复现fedlora的实验结果。

**Comment by jingluo168** [comment]
> 我在尝试复现的时候，发现fedlora这个baseline效果非常差，不知道作者能否开源相关代码？

您好，想请教您，是怎样解决fedlora这个问题的
